<?php
/**
 * Cybage Color Swatches Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Color Swatches Plugin
 * @package    Cybage_Swatches
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */

$productAttribute = $this->checkConfAttribute();
$activeProduct    = $this->getProduct();
?>

<?php if($activeProduct->isSaleable()):?>
    <dl>
    <?php if(!empty($productAttribute)):

        foreach($productAttribute as $attributeValue): 
        //if($attributeValue['attribute_id'] == "272"):
        ?>
        
        <dt id="title-<?php echo $attributeValue['attribute_id'] ?>-<?php echo $activeProduct->getEntityId() ?>">
            <label class="required"><em>*</em> <?php echo $attributeValue['label']; ?></label>
        </dt>
        <dd class="last">
            <div class="input-box" style="margin: 2px;">
                <select name="superattributeValue[<?php echo $attributeValue['attribute_id'] ?>]" id="attribute<?php echo $attributeValue['attribute_id'] ?>-<?php echo $activeProduct->getEntityId() ?>" class="required-entry no-display super-attribute-select-<?php echo $activeProduct->getEntityId() ?>">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                </select>
              </div>
        </dd>
        <?php// endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    </dl>
    <script type="text/javascript">
        listingSwatches = new Product.Config(<?php echo $this->getJsonConfig() ?>);
        optionsPrice['<?php echo $activeProduct->getId();?>'] = new Product.OptionsPrice(<?php echo $this->getPriceForConfig();?>);
    </script>
<?php endif;?>